# Generated by Django 4.1.13 on 2023-12-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created']},
        ),
    ]
