# Generated by Django 4.1.13 on 2024-01-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
